#!/bin/bash

header=""
getflag(){
	case $1 in
		name)
		 	flag=1
			;;
		uid)
			flag=3
			;;
		gid)
			flag=4
		 	;;
		comment)
			flag=5
		 	;;
		homedir)
			flag=6
		 	;;
		shell)
			flag=7
		 	;;
		*)
			:
			;;
	esac
	
}
if [ $# -eq 0 ];
then 
	echo "use default setting"
	echo -e "username:uid:gid:comment:homedir:shell\n$(cat /etc/passwd|cut -d ":" -f 1,3-8|sort -t ":" -k 1)"|column -t -s ":"
fi

while getopts "s:o:" opt
do
	case $opt in
	S)
		echo "Sort"
		;;
	o)
		echo "choose header"
		IFS=","
		array=$OPTARG
		for arg in $array
		do
			getflag $arg
			#echo $flag
			if [ $flag ] && [ "$flag" != 0 ];
			then
				if [ ! $header ];
				then
					header="\$$flag"
				else
					header="$header\":\"\$$flag"
				fi
				
			fi

			if [[ $arg =~ ^- ]];
			then
				:
			else
				if [ ! $title ];
				then
					title=$arg
				else
					title="$title:$arg"
				fi
				
			fi
			
			flag=""
		done
		;;
	*)
		:
		;;
	esac
done

shift $(( $OPTIND-1 ))
#echo $header
echo -e "$title\n$(cat /etc/passwd|awk -F ":" '{print '''$header'''}')"|column -t -s ":"
