#!/bin/bash

content=""
title=""
flag=""
sort_opt=""
sort_index=""
data=""
getflag(){
	case $1 in
		name)
		 	flag=1
			;;
		uid)
			flag=3
			;;
		gid)
			flag=4
		 	;;
		comment)
			flag=5
		 	;;
		homedir)
			flag=6
		 	;;
		shell)
			flag=7
		 	;;
		*)
			:
			;;
	esac
	
}

data=$(cat /etc/passwd|awk -F ":" '{ if($7 == "/sbin/nologin"){print $0":system\\n" }else{print $0":general\\n"}}')
if [ $# -eq 1 ];
then
	if [ "$1" == "system" ];
	then
		echo "System User:"
		echo -e $data| sed 's/^\s//g'|awk -F ":" '{ if($8 == "system"){print $1":"$3":"$4":"$5":"$6":"$7} }'|column -s ":" -t
	elif [ "$1" == "general" ];
	then
		echo "General User:"
		echo -e $data| sed 's/^\s//g'|awk -F ":" '{ if($8 == "general"){print $1":"$3":"$4":"$5":"$6":"$7} }'|column -s ":" -t
	else
		if [[ $1 =~ ^- ]];
		then 
			:
		else 
			echo "error,no option"
		fi
	fi
elif [ $# -eq 0 ];
then
	echo "System User:"
	echo -e $data| sed 's/^\s//g'|awk -F ":" '{ if($8 == "system"){print $1":"$3":"$4":"$5":"$6":"$7} }'|column -s ":" -t
	echo "General User:"
	echo -e $data| sed 's/^\s//g'|awk -F ":" '{ if($8 == "general"){print $1":"$3":"$4":"$5":"$6":"$7} }'|column -s ":" -t	
fi

while getopts "s:o:h" opt
do
	case $opt in
	s)
		echo "Sort"
		sort_index=$(echo "$@"|awk '{ for(i=1;i<=NF;i++){ if($i =="-o"){i=i+1;print $i}}}')
		sort_index=$(echo $sort_index|awk '{ for(i=1;i<=NF;i++){ if($i == "'''$OPTARG'''"){print i}}}')
		if [[ $OPTARG =~ "uid"|"gid" ]];
		then 
			sort_opt="-n"
		elif [[ $OPTARG =~ "name"|"comment"|"homedir"|"shell" ]];
		then
			sort_opt=""
		else
			echo "error,don't have this option"
		fi		
		;;
	o)
		echo "choose header"
		IFS=","
		array=$OPTARG
		for arg in $array
		do
			getflag $arg
			#echo $flag
			if [ $flag ] && [ "$flag" != 0 ];
			then
				if [ ! $content ];
				then
					content="\$$flag"
				else
					content="$content\":\"\$$flag"
				fi
				
			fi

			if [[ $arg =~ ^- ]];
			then
				:
			else
				if [ ! $title ];
				then
					title=$arg
				else
					title="$title:$arg"
				fi
				
			fi
			
			flag=""
		done
		;;
	h)
		echo "help"
		exit 0
		;;
	*)
		:
		;;
	esac
done

shift $(( $OPTIND-1 ))
if [ ! $sort_index ];
then
	sort_index=1
fi
echo -e "$title\n$(cat /etc/passwd|awk -F ":" '{print '''$content'''}'|sort $sort_opt -t ":" -k $sort_index)"|column -t -s ":"
