#!/bin/bash

content=""
title=""
flag=""
sort_opt=""
sort_index=""
getflag(){
	case $1 in
		name)
		 	flag=1
			;;
		uid)
			flag=3
			;;
		gid)
			flag=4
		 	;;
		comment)
			flag=5
		 	;;
		homedir)
			flag=6
		 	;;
		shell)
			flag=7
		 	;;
		*)
			:
			;;
	esac
	
}
if [ $# -eq 0 ];
then 
	echo "use default setting"
	echo -e "username:uid:gid:comment:homedir:shell\n$(cat /etc/passwd|cut -d ":" -f 1,3-8|sort -t ":" -k 1)"|column -t -s ":"
fi

while getopts "s:o:h" opt
do
	case $opt in
	s)
		echo "Sort"
		sort_index=$(echo "$@"|awk '{ for(i=1;i<=NF;i++){ if($i =="-o"){i=i+1;print $i}}}')
		sort_index=$(echo $sort_index|awk '{ for(i=1;i<=NF;i++){ if($i == "'''$OPTARG'''"){print i}}}')
		if [[ $OPTARG =~ "uid"|"gid" ]];
		then 
			sort_opt="-n"
		elif [[ $OPTARG =~ "name"|"comment"|"homedir"|"shell" ]];
		then
			sort_opt=""
		else
			echo "error,don't have this option"
		fi		
		;;
	o)
		echo "choose header"
		IFS=","
		array=$OPTARG
		for arg in $array
		do
			getflag $arg
			#echo $flag
			if [ $flag ] && [ "$flag" != 0 ];
			then
				if [ ! $content ];
				then
					content="\$$flag"
				else
					content="$content\":\"\$$flag"
				fi
				
			fi

			if [[ $arg =~ ^- ]];
			then
				:
			else
				if [ ! $title ];
				then
					title=$arg
				else
					title="$title:$arg"
				fi
				
			fi
			
			flag=""
		done
		;;
	h)
		echo "help"
		exit 0
		;;
	*)
		:
		;;
	esac
done

shift $(( $OPTIND-1 ))

echo -e "$title\n$(cat /etc/passwd|awk -F ":" '{print '''$content'''}'|sort $sort_opt -t ":" -k $sort_index)"|column -t -s ":"
